### PR TITLE
Parse Input Variables

### LINKED ISSUE #4: Parse input and output variables
Parse the full set of input variable attributes.
Grammar needs to be extended

### PR DESCRIPTION
**Pull request by kayman-mk**
Closes #4

### CODE REVIEW

**Comment by obfischer** [comment]
I merged the first PR. Is one does not build. Could you please rebase it and fix the compile errors?

**Comment by kayman-mk** [comment]
Yeah, still work in progress. Have to find a good solution to parse the HCL files.

**Comment by kayman-mk** [comment]
Everything fixed and ready. Could you please keep an eye on the parser logic?

**Comment by obfischer** [comment]
👍

**Pull request merged**
